// Generated by CoffeeScript 1.3.3
(function() {
  var filesystem, fs, path;

  fs = require('fs-extra');

  path = require('path');

  module.exports = filesystem = function(Store, config) {
    Store.prototype.write = function(style, file, cb) {
      var destFile;
      destFile = this.filePath(style);
      return fs.mkdir(path.dirname(destFile), function(err) {
        if (err != null) {
          return cb(err);
        }
        return fs.copy(file, destFile, cb);
      });
    };
    Store.prototype["delete"] = function(style, cb) {
      return fs.unlink(this.filePath(style), cb);
    };
    return Store.prototype.filePath = function(style) {
      return path.join(config.dir, this.path(style, this.attachedFile.pathAttributes));
    };
  };

}).call(this);
