// Generated by CoffeeScript 1.6.3
(function() {
  var filesystem, fs, path;

  fs = require('fs-extra');

  path = require('path');

  module.exports = filesystem = function(Store, config) {
    var copyFile;
    copyFile = function(srcFile, destFile, cb) {
      var fdr, fdw, nodeFs;
      nodeFs = require("fs");
      fdr = nodeFs.createReadStream(srcFile);
      fdw = nodeFs.createWriteStream(destFile);
      fdr.on("end", function() {
        return cb(null);
      });
      return fdr.pipe(fdw);
    };
    Store.prototype.write = function(style, file, cb) {
      var destFile;
      destFile = this.filePath(style);
      return fs.mkdirs(path.dirname(destFile), function(err) {
        if (err != null) {
          return cb(err);
        }
        return copyFile(file, destFile, cb);
      });
    };
    Store.prototype["delete"] = function(style, cb) {
      return fs.unlink(this.filePath(style), function(err) {
        if ((err != null ? err.code : void 0) === 'ENOENT') {
          console.error("Filesystem: file not found for delete. Ignoring", err.path);
          return cb();
        }
        return cb(err);
      });
    };
    return Store.prototype.filePath = function(style) {
      return path.join(config.dir, this.path(style));
    };
  };

}).call(this);
