// Generated by CoffeeScript 1.6.3
(function() {
  var knox, s3, _;

  knox = require('knox');

  _ = require('underscore');

  module.exports = s3 = function(Store, config) {
    var client, defaultHeaders;
    client = knox.createClient({
      key: config.access_key_id,
      secret: config.secret_access_key,
      bucket: config.bucket
    });
    defaultHeaders = config.s3Headers || {};
    Store.prototype.write = function(style, file, cb) {
      var path;
      path = this.path(style);
      console.log("S3: writing " + path);
      return client.putFile(file, this.path(style), _(defaultHeaders).extend(this.attachedFile.s3Headers, {
        'Content-Type': this.attachedFile.file.type
      }), function(err, res) {
        if (err && (res == null)) {
          return cb(err);
        }
        if (res.statusCode !== 200) {
          if (err == null) {
            err = new Error("" + res.statusCode + " Error from S3 put");
          }
        }
        return cb(err, res);
      });
    };
    return Store.prototype["delete"] = function(style, cb) {
      var path;
      path = this.path(style);
      console.log("S3: deleting " + path);
      return client.deleteFile(this.path(style), function(err, res) {
        if (err && (res == null)) {
          return cb(err);
        }
        if (res.statusCode !== 204) {
          if (err == null) {
            err = new Error("" + res.statusCode + " Error from S3 delete");
          }
        }
        return cb(err, res);
      });
    };
  };

}).call(this);
