// Generated by CoffeeScript 1.3.3
(function() {
  var async, attachments, extensions, imagemagick, mkdirp;

  imagemagick = require('imagemagick');

  mkdirp = require('mkdirp');

  async = require('async');

  extensions = {
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/gif": ".gif"
  };

  module.exports = attachments = function(config) {
    var Attachments;
    return {
      Attachment: Attachments = (function() {

        function Attachments(file, options) {
          this.file = file;
          this.options = options != null ? options : {};
          this.id = this.options.id || new Date().getTime();
          this.name = this.options.name || this.file.name.replace(/(\..*?)$/, '');
          this.extension = extensions[this.file.type];
        }

        Attachments.prototype.conversions = function() {
          var conversion, conversions, style;
          return conversions = (function() {
            var _ref, _results,
              _this = this;
            _ref = config.styles;
            _results = [];
            for (style in _ref) {
              conversion = _ref[style];
              _results.push((function(style, conversion) {
                var args, destFile, dir, groups;
                dir = _this.dir(style);
                destFile = _this.path(style);
                args = [_this.file.path, '-resize', conversion];
                if (groups = conversion.match(/^(.*)\^$/)) {
                  args = args.concat(['-gravity', 'center', '-extent', groups[1]]);
                }
                args.push(destFile);
                return {
                  style: style,
                  path: destFile,
                  args: args,
                  convert: function(cb) {
                    return mkdirp(dir, function(err) {
                      if (err != null) {
                        return cb(err);
                      }
                      return imagemagick.convert(args, cb);
                    });
                  }
                };
              })(style, conversion));
            }
            return _results;
          }).call(this);
        };

        Attachments.prototype.convert = function(cb) {
          var c, conversions;
          conversions = this.conversions();
          return async.series((function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = conversions.length; _i < _len; _i++) {
              c = conversions[_i];
              _results.push(c.convert);
            }
            return _results;
          })(), cb);
        };

        Attachments.prototype.dir = function(style) {
          return "" + config.storage.dir.path + "/" + config.prefix + "/" + this.id + "/" + style;
        };

        Attachments.prototype.path = function(style) {
          return "" + (this.dir(style)) + "/" + this.name + this.extension;
        };

        return Attachments;

      })()
    };
  };

}).call(this);
