// Generated by CoffeeScript 1.3.3
(function() {
  var knox, s3;

  knox = require('knox');

  module.exports = s3 = function(Store, config) {
    var client;
    client = knox.createClient({
      key: config.access_key_id,
      secret: config.secret_access_key,
      bucket: config.bucket
    });
    return Store.prototype.write = function(style, file, cb) {
      var path;
      path = this.path(style);
      console.log("S3: writing " + path);
      return client.putFile(file, this.path(style), {
        'Content-Type': this.attachment.file.type
      }, cb);
    };
  };

}).call(this);
