// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = {
    configure: function(config) {
      return require('./storage').configure(config);
    },
    Processor: require('./processor'),
    AttachedFile: require('./attached_file'),
    hasAttachment: require('./plugin')
  };

}).call(this);
