// Generated by CoffeeScript 1.3.3
(function() {
  var Attachment, Processor, Store, exports, extensions;

  Processor = require("./processor").Processor;

  Store = require("./storage").Store;

  extensions = {
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/gif": ".gif"
  };

  exports = module.exports = Attachment = (function() {

    function Attachment(id, options) {
      var _ref;
      this.id = id;
      this.options = options != null ? options : {};
      if ((_ref = this.id) == null) {
        this.id = new Date().getTime();
      }
      this.prefix = this.options.prefix || "default";
      this.styles = this.options.styles || [];
      this.store = new Store(this);
      if (this.options.file != null) {
        this.file(this.options.file);
      }
    }

    Attachment.prototype.file = function(file) {
      this.file = file;
      this.extension = extensions[this.file.type];
      return this.name = this.options.name || this.file.name.replace(/(\..*?)$/, '');
    };

    Attachment.prototype.save = function(cb) {
      var processor,
        _this = this;
      this.store.pendingWrites.push({
        style: 'original',
        file: this.file.path
      });
      processor = new Processor(this.file, {
        styles: this.styles
      });
      processor.on('convert', function(result) {
        return _this.store.pendingWrites.push(result);
      });
      processor.on('done', function() {
        return _this.store.flushWrites(cb);
      });
      processor.on('error', cb);
      return processor.convert();
    };

    Attachment.prototype.path = function(style) {
      return this.store.path(style);
    };

    return Attachment;

  })();

}).call(this);
