// Generated by CoffeeScript 1.3.3
(function() {
  var Attachment, Processor, Storage, exports, extensions;

  Processor = require("./processor");

  Storage = require("./storage");

  extensions = {
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/gif": ".gif"
  };

  exports = module.exports = Attachment = (function() {

    function Attachment(id, options) {
      var _ref, _ref1;
      this.id = id;
      this.options = options != null ? options : {};
      if ((_ref = this.id) == null) {
        this.id = new Date().getTime();
      }
      this.prefix = this.options.prefix || "default";
      this.styles = this.options.styles || [];
      this.store = new Storage(this);
      this.file = this.options.file;
      if (this.options.name) {
        this.fileName = this.options.name;
      } else if (this.file) {
        this.fileName = this.file.name;
        if (extensions[this.file.type]) {
          if ((_ref1 = this.fileName) != null) {
            _ref1.replace(/(\..*?)$/, extensions[this.file.type]);
          }
        }
      }
    }

    Attachment.prototype.save = function(cb) {
      var processor,
        _this = this;
      this.store.pendingWrites.push({
        style: 'original',
        file: this.file.path
      });
      processor = new Processor(this.file, {
        styles: this.styles
      });
      processor.on('convert', function(result) {
        return _this.store.pendingWrites.push(result);
      });
      processor.on('done', function() {
        return _this.store.flushWrites(cb);
      });
      processor.on('error', cb);
      return processor.convert();
    };

    Attachment.prototype.path = function(style) {
      return this.store.path(style);
    };

    Attachment.prototype.url = function(style) {
      return this.store.url(style);
    };

    return Attachment;

  })();

}).call(this);
