// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    configure: function(config) {
      require('./storage').configure(config.storage);
      return console.log("Configured storage", config.storage);
    },
    Processor: require('./processor'),
    Attachment: require('./attachment'),
    hasAttachment: require('./plugin')
  };

}).call(this);
